### ISSUE TITLE
Bug Report: Game Crash when open

### ISSUE THREAD

**Issue by TwilightBob** [Kaique62/Kade-Engine-1.5.1-Android#1]
Idk when i open it then crash or smh i or it is my fault for adding a character? 
I did code the icons and the character.hx thing so idk

**Comment by Kaique62** [comment]
yo, just delete this 	
	
                #if polymod
		polymod.Polymod.init({modRoot: "mods", dirs: ['introMod']});
		#end

it's on line 56 in title state

**Comment by TwilightBob** [comment]
Thanks for the help
